name: Client E2E tests
on:
  push:
    branches:
      - main
      - ci/tests
jobs:
  cypress-e2e-tests:
    runs-on: self-hosted
    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      APP_MAIL: ${{secrets.APP_MAIL}}
      SES_ACCESS: ${{secrets.SES_ACCESS}}
      SES_SECRET: ${{secrets.SES_SECRET}}
      SES_REGION: ${{secrets.SES_REGION}}
      JWT_SECRET: ${{secrets.JWT_SECRET}}
      JWT_SECRET_REF: ${{secrets.JWT_SECRET_REF}}
      JWT_EXPIRY: ${{secrets.JWT_EXPIRY}}
      JWT_EXPIRY_REF: ${{secrets.JWT_EXPIRY_REF}}
      MAX_REFRESH: ${{secrets.MAX_REFRESH}}
      CYPRESS_MAILSAC_KEY: ${{secrets.CYPRESS_MAILSAC_KEY}}
      CYPRESS_MAILSAC_MAIL: ${{secrets.CYPRESS_MAILSAC_MAIL}}
      CYPRESS_MAIL_VERIFIED: ${{secrets.CYPRESS_MAIL_VERIFIED}}
      CYPRESS_MAIL_UNVERIFIED: ${{secrets.CYPRESS_MAIL_UNVERIFIED}}
      CYPRESS_MAIL_PASS: ${{secrets.CYPRESS_MAIL_PASS}}
      MAIL_VERIFIED: ${{secrets.MAIL_VERIFIED}}
      MAIL_UNVERIFIED: ${{secrets.MAIL_UNVERIFIED}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2

      - name: Install express app dependencies
        run: npm install
        working-directory: backend

      - name: Install client dependencies
        run: npm install
        working-directory: frontend

      - name: Run express server
        run: npm run dev &
        working-directory: backend

      - name: Run client server
        run: npm run dev &
        working-directory: frontend

      - name: Run tests
        run: npx cypress run
        working-directory: frontend
